server:
  port: 8081

spring:
  application:
    name: quotation-ms
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://postgres:5432/quotation_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: redis
      port: 6379
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://schema-registry:8081

grpc:
  client:
    ml-risk-ms:
      address: 'discovery:///ml-risk-ms'
      enableKeepAlive: true
      negotiationType: plaintext

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
